name: dart_code_metrics
version: 6.0.0
description: Software analytics tool that helps developers analyse and improve software quality.
homepage: https://dcm.dev/
repository: https://github.com/dart-code-checker/dart-code-metrics
issue_tracker: https://github.com/dart-code-checker/dart-code-metrics/issues
documentation: https://dcm.dev/docs/getting-started/

environment:
  sdk: ^3.2.3

platforms:
  linux:
  windows:
  macos:

dependencies:
  analyzer: ^6.4.0
  analyzer_plugin: ^0.11.3
  ansicolor: ^2.0.2
  args: ^2.4.2
  collection: ^1.18.0
  crypto: ^3.0.3
  dart_code_metrics_presets: ^1.8.0
  file: ^6.1.4
  glob: ^2.1.2
  html: ^0.15.4
  http: ^1.2.0
  meta: ^1.11.0
  path: ^1.9.0
  platform: ^3.1.0 # overridden for lowest versions compatibility
  pub_updater: ^0.3.1
  source_span: ^1.10.0
  uuid: ^3.0.7
  xml: ^6.5.0
  yaml: ^3.1.2

dev_dependencies:
  coverage: ^1.7.2
  intl: ^0.19.0
  lints: ^2.1.1
  mocktail: ^1.0.3
  test: ^1.25.1

  # internal package, used only in tests data
  test_lints:
    path: ./test/resources/test_lints

executables:
  metrics:
